GondolinWebApp/GondolinWeb/Areas/Application/Controllers/TasksController.cs
using GondolinWeb.Areas.Application.Models;
using GondolinWeb.Areas.Identity.Data;
using GondolinWeb.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using System.Dynamic;
using System.Security.Claims;
using System.Threading.Tasks;
using Task = GondolinWeb.Areas.Application.Models.Task;

namespace GondolinWeb.Areas.Application.Controllers
{
    /// <summary>
    /// Class which represents the functionality required for handling tasks.
    /// "[Authorize]" added to protect behind authentication.
    /// </summary>
    [Authorize]
    [Area("Application")]
    public class TasksController : Controller
    {
        /// <summary>
        /// Database Context for application.
        /// </summary>
        private readonly GondolinWebIdentityDBContext _context;

        /// <summary>
        /// Instantiates new instance of the Controller class.
        /// </summary>
        /// <param name="context">DB Context injected.</param>
        public TasksController(GondolinWebIdentityDBContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Return the index view, creates a list from the UserTask table based on the user that is signed in.
        /// </summary>
        /// <returns>View with the users tasks model.</returns>
        /// GET: Application/Tasks
        public async Task<IActionResult> Index(string sortOrder, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = sortOrder == "Name" ? "name_desc" : "Name";
            ViewData["DateSortParm"] = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            ViewData["CatSortParm"] = sortOrder == "CatName" ? "CatName_desc" : "CatName";
            ViewData["ProjSortParm"] = sortOrder == "ProjName" ? "ProjName_desc" : "ProjName";

            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            var taskList = from t in _context.Tasks
                           join p in _context.Project on t.ProjectID equals p.ID
                           join ur in _context.UserProjects on p.ID equals ur.ProjectId
                           where ur.UserId == userId
                               && t.IsArchived == false
                               && t.IsQuickTask == false
                               && t.IsFavorite == false
                           select t;

            ApplicationUser appUser = _context.Users.Where(u => u.Id == userId).First();

            ViewBag.UserQuickProject = appUser.QuickProjectID;
            ViewBag.UserCategories = new ListService(_context).GetListOfUserCategories(this.User.FindFirstValue(ClaimTypes.NameIdentifier));

            ViewBag.Theme = appUser.Theme;

            ViewBag.Project = new ListService(_context).GetListOfProjects(this.User.FindFirstValue(ClaimTypes.NameIdentifier), appUser.QuickProjectID);

            switch (sortOrder)
            {
                case "name_desc":
                    taskList = taskList.OrderByDescending(t => t.Name);
                    break;

                case "Name":
                    taskList = taskList.OrderBy(t => t.Name);
                    break;

                case "CatName_desc":
                    taskList = taskList.OrderByDescending(t => t.CategoryName);
                    break;

                case "CatName":
                    taskList = taskList.OrderBy(t => t.CategoryName);
                    break;

                case "ProjName_desc":
                    taskList = taskList.OrderByDescending(t => t.ProjectID);
                    break;

                case "ProjName":
                    taskList = taskList.OrderBy(t => t.ProjectID);
                    break;

                case "date_desc":
                    taskList = taskList.OrderByDescending(t => t.RequiredDate);
                    break;

                default:
                    taskList = taskList.OrderBy(t => t.RequiredDate);
                    break;
            }
            int pageSize = 5;

            var favTasks = from t in _context.Tasks
                           join p in _context.Project on t.ProjectID equals p.ID
                           join ur in _context.UserProjects on p.ID equals ur.ProjectId
                           where ur.UserId == userId
                               && t.IsArchived == false
                               && t.IsQuickTask == false
                               && t.IsFavorite == true
                           select t;

            var favs = await favTasks.AsNoTracking().ToListAsync();
            var pgTaskList = await PaginatedList<Task>.CreateAsync(taskList.AsNoTracking(), pageNumber ?? 1, pageSize);

            dynamic taskModel = new ExpandoObject();
            taskModel.FavTasks = favs;
            taskModel.TaskList = pgTaskList;

            return this.View(taskModel);
        }

        //TODO CC: The detail task was built by the template, may need to be removed at later time.
        // GET: Application/Tasks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tasks == null)
            {
                return NotFound();
            }

            ApplicationUser appUser = _context.Users.Where(u => u.Id == this.User.FindFirstValue(ClaimTypes.NameIdentifier)).First();

            var task = await _context.Tasks
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);

            if (task == null)
            {
                return NotFound();
            }

            ViewBag.Project = new ListService(_context).GetListOfProjects(this.User.FindFirstValue(ClaimTypes.NameIdentifier), appUser.QuickProjectID).FirstOrDefault(p => p.ID == task.ProjectID);

            return View(task);
        }

        public async Task<IActionResult> Report(int? id)
        {
            if (id == null || _context.Tasks == null)
            {
                return NotFound();
            }

            ApplicationUser appUser = _context.Users.Where(u => u.Id == this.User.FindFirstValue(ClaimTypes.NameIdentifier)).First();
            var task = await _context.Tasks
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);

            if (task == null)
            {
                return NotFound();
            }

            ViewBag.User = appUser.FirstName + " " + appUser.LastName;
            var project = new ListService(_context).GetListOfProjects(this.User.FindFirstValue(ClaimTypes.NameIdentifier), appUser.QuickProjectID).FirstOrDefault(p => p.ID == task.ProjectID);

            ViewBag.Theme = appUser.Theme;

            if (project != null)
            {
                ViewBag.Project = project;
            }

            return View(task);
        }

        /// <summary>
        /// Action which returns the create view.
        /// The ViewBag.Project contains a list that populates the projects drop down.
        /// Gets the ApplicationUser, passed the application user ID and QuickProjectId into the list service.
        /// Return the filtered list of active projects.
        /// </summary>
        /// <returns>Create view.</returns>
        /// GET: Application/Tasks/Create
        public async Task<IActionResult> CreateAsync()
        {
            ApplicationUser appUser = _context.Users.Where(u => u.Id == this.User.FindFirstValue(ClaimTypes.NameIdentifier)).First();
            ViewBag.Project = new ListService(_context).GetListOfProjects(this.User.FindFirstValue(ClaimTypes.NameIdentifier), appUser.QuickProjectID);
            ViewBag.Category = new ListService(_context).GetListOfUserCategories(this.User.FindFirstValue(ClaimTypes.NameIdentifier));

            ViewBag.Theme = appUser.Theme;

            ViewBag.Today = DateTime.Now.ToString("yyyy-MM-dd");

            return View();
        }

        /// <summary>
        /// Processes user input from the form.
        /// Adds the task to the task table, adds userID and taskId to the UserTask table
        /// </summary>
        /// <param name="task">Task which the user created.</param>
        /// <returns></returns>
        // POST: Application/Tasks/Create
        // To protect from over posting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CategoryID,Description,IsComplete,Name,ProjectID,RequiredDate,CategoryName")] Task task)
        {
            if (ModelState.IsValid)
            {
                if (task.ProjectID == 0)
                {
                    ApplicationUser user = _context.Users.Where(u => u.Id == this.User.FindFirstValue(ClaimTypes.NameIdentifier)).First();
                    task.ProjectID = user.QuickProjectID;
                }
                task.CreationDate = DateTime.Now;
                _context.Add(task);

                // Below is functionality required to add custom categories.
                // Functionality could be moved to menthod and called for simplification.
                ApplicationUser appUser = _context.Users.Where(u => u.Id == this.User.FindFirstValue(ClaimTypes.NameIdentifier)).First();

                // Try to get category from TaskCategories table.
                var cat = (from tc in _context.TaskCategories
                           where tc.UserId == appUser.Id
                                   && tc.Name == task.CategoryName
                                   && tc.IsArchived == false
                           select tc).FirstOrDefault();

                // If category does not exist add new TaskCategory.

GondolinWebApp/GondolinWeb/Controllers/HomeController.cs
using GondolinWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GondolinWeb.Controllers
{
    public class Home : Controller
    {
        private readonly ILogger<Home> _logger;

        public Home(ILogger<Home> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated == true)
            {
                return RedirectToAction("index", "Home", new { area = "Application" });
            }
            return View();
        }

        public IActionResult HomeSite()
        {
            //TODO: This is the area.
            if (User.Identity.IsAuthenticated == true)
            {
                return RedirectToAction("index", "Home", new { area = "Application" });
            }
            return View("Index");
        }

        public IActionResult Faq()
        {
            return View();
        }

        public IActionResult Team()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GondolinWebApp/GondolinWeb/Areas/Application/Views/Home/Index.cshtml
@using GondolinWeb.Areas.Identity.Data
@using Microsoft.AspNetCore.Identity
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@inject UserManager<ApplicationUser> userManager;
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Application";
    ApplicationUser user = await userManager.GetUserAsync(User);
}


<div>
    <div class="row">
        <div class="col">
            <h1>Dashboard <i class="bi bi-question-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="Manage your Projects and Tasks here."></i></h1>
        </div>
        <div class="col text-end">
            <div class="dropdown">
                <button onclick="myFunction()" class="dropbtn">Change Theme <i class="bi bi-question-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="Change the colors of tables and buttons, for better readability."></i></button>
                <div id="myDropdown" class="dropdown-content">
                    <a asp-area="Application" asp-controller="Home" asp-action="GreenTheme">Default Theme</a>
                    <a asp-area="Application" asp-controller="Home" asp-action="DarkTheme">Dark Theme</a>
                    <a asp-area="Application" asp-controller="Home" asp-action="LightTheme">Light Theme</a>
                </div>
            </div>
        </div>
    </div>
    <hr class="dashboard-line" />
    <h2 class="text-center"><strong>Hello, @user.FirstName!</strong>&nbsp;&nbsp;What would you like to do today?</h2>
        <hr class="dashboard-line" />
</div>

<div class="row">
    <div class="col">
        <div class="row">
            <div class="col">
                <h3>
                    Current Projects <i class="bi bi-question-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="Click on Project Name to manage a Project."></i>
                </h3>
            </div>
            <div class="col text-end">
                <a class="btn btn-sm btn-color" asp-controller="Projects" asp-action="Create">Create New Project</a>
            </div>
        </div>
        @await Html.PartialAsync("~/Areas/Application/Views/Shared/_DashboardProjectsPartial.cshtml", user.Projects )
    </div>

    <div class="col">
        <div class="row">
            <div class="col">
                <h3>Outstanding Tasks <i class="bi bi-question-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="Click on Task Name to go to that Task's Project."></i></h3>
            </div>
            <div class="col text-end">
                <a class="btn btn-sm btn-color" asp-controller="Tasks" asp-action="Create">Create New Task</a>
            </div>
        </div>
        
        @await Html.PartialAsync("~/Areas/Application/Views/Shared/_DashboardTasksPartial.cshtml", user.Tasks )
    </div>
</div><br /><br />


<hr class="dashboard-line" />
<div id="quicklist-container" class="container m-auto w-75">
    <h3 class="text-center">QuickList <i class="bi bi-question-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="A simple To-Do List with Tasks that are not in any Project."></i></h3>
        <div id="quickList"> </div>
        
</div><br /><br />

@section Scripts{
        <script>
        $('#quickList').load('@Url.Action("QuickList", "Tasks")');
        </script>
}