GondolinWebApp/GondolinWeb/Areas/Application/Models/Project.cs
using System.ComponentModel.DataAnnotations;

namespace GondolinWeb.Areas.Application.Models
{
    /// <summary>
    /// Class which represents a project.
    /// </summary>
    public class Project
    {
        /// <summary>
        /// Gets or sets the ID value for the project.
        /// </summary>
        public int ID { get; set; }

        /// <summary>
        /// Gets the date the project was created.
        /// </summary>
        [Required]
        [DataType(DataType.DateTime)]
        public DateTime CreationDate { get; set; }

        /// <summary>
        /// Gets or sets the project detailed description.
        /// </summary>
        [StringLength(1000)]
        [MaxLength(500, ErrorMessage = "The {0} must not be more than {1} characters long.")]
        [RegularExpression(@"^[a-zA-Z0-9-+()&%$#@!:.,-?\s][^;`']*$",
         ErrorMessage = "Some special characters are not allowed such as ; ' \\ <")]
        [DataType(DataType.MultilineText)]
        public string? Description { get; set; }

        /// <summary>
        /// Gets or sets the IsComplete status for the project.
        /// </summary>
        [Display(Name = "Is Complete?")]
        public bool IsComplete { get; set; }

        /// <summary>
        /// Gets or sets the IsArchived status for the project.
        /// </summary>
        public bool IsArchived { get; set; }

        /// <summary>
        /// Gets or sets the name of the project.
        /// </summary>
        [Required]
        [DataType(DataType.Text)]
        [MinLength(2, ErrorMessage = "The {0} must be at least {1} characters long.")]
        [MaxLength(30, ErrorMessage = "The {0} must not be more than {1} characters long.")]
        [RegularExpression(@"^[a-zA-Z0-9-+()&%$#@!:.,-?\s][^;`']*$",
         ErrorMessage = "Some special characters are not allowed such as ; ' \\ <")]
        public string? Name { get; set; }

        /// <summary>
        /// Gets or sets the date the project is to be completed by. Can be NULL.
        /// </summary>
        [DataType(DataType.DateTime)]
        [Display(Name = "Required Date")]
        public DateTime? RequiredDate { get; set; }
    }
}

GondolinWebApp/GondolinWeb/Areas/Application/Controllers/ProjectsController.cs
using GondolinWeb.Areas.Application.Models;
using GondolinWeb.Areas.Identity.Data;
using GondolinWeb.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using Project = GondolinWeb.Areas.Application.Models.Project;

namespace GondolinWeb.Areas.Application.Controllers
{
    [Authorize]
    [Area("Application")]
    public class ProjectsController : Controller
    {
        private readonly GondolinWebIdentityDBContext _context;

        public ProjectsController(GondolinWebIdentityDBContext context)
        {
            _context = context;
        }

        // GET: Application/Projects
        public async Task<IActionResult> Index(string sortOrder, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = sortOrder == "Name" ? "name_desc" : "Name";
            ViewData["DateSortParm"] = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";

            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            ApplicationUser appUser = _context.Users.Where(u => u.Id == userId).First();

            var projectList = (from p in _context.Project
                               join ur in _context.UserProjects on p.ID equals ur.ProjectId
                               where ur.UserId == userId
                                        && p.IsComplete == false
                                        && p.IsArchived == false
                                        && p.ID != appUser.QuickProjectID
                               select p);

            switch (sortOrder)
            {
                case "name_desc":
                    projectList = projectList.OrderByDescending(t => t.Name);
                    break;

                case "Name":
                    projectList = projectList.OrderBy(t => t.Name);
                    break;

                case "date_desc":
                    projectList = projectList.OrderByDescending(t => t.RequiredDate);
                    break;

                default:
                    projectList = projectList.OrderBy(t => t.RequiredDate);
                    break;
            }

            ViewBag.Theme = appUser.Theme;

            int pageSize = 10;

            return this.View(await PaginatedList<Project>.CreateAsync(projectList.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Application/Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Project == null)
            {
                return NotFound();
            }

            ApplicationUser appUser = _context.Users.Where(u => u.Id == this.User.FindFirstValue(ClaimTypes.NameIdentifier)).First();
            var project = new ListService(_context).GetListOfProjects(this.User.FindFirstValue(ClaimTypes.NameIdentifier), appUser.QuickProjectID).FirstOrDefault(p => p.ID == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Application/Projects/Create
        public async Task<IActionResult> Create()
        {
            ApplicationUser appUser = _context.Users.Where(u => u.Id == this.User.FindFirstValue(ClaimTypes.NameIdentifier)).First();

            ViewBag.Theme = appUser.Theme;

            ViewBag.Today = DateTime.Now.ToString("yyyy-MM-dd");

            return View();
        }

        // POST: Application/Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Description,IsComplete,Name,RequiredDate")] Project project, string submitbutton)
        {
            if (ModelState.IsValid)
            {
                project.CreationDate = DateTime.Now;
                _context.Add(project);
                _context.SaveChanges();
                _context.UserProjects.Add(new UserProject { UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier), ProjectId = project.ID });
                await _context.SaveChangesAsync();
            }
            else
            {
                submitbutton = string.Empty;
            }

            switch (submitbutton)
            {
                case "IndexCreate":
                    // I'm done button
                    return RedirectToAction(nameof(Index));

                case "AddTasksCreate":
                    // Add Task button
                    return RedirectToAction(nameof(Edit), new { id = project.ID });

                default:
                    // this is not called or used but will return the current view
                    return View(nameof(Create));
            }
        }

        // GET: Application/Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Project == null)
            {
                return NotFound();
            }

            ApplicationUser appUser = _context.Users.Where(u => u.Id == this.User.FindFirstValue(ClaimTypes.NameIdentifier)).First();
            var project = new ListService(_context).GetListOfProjects(this.User.FindFirstValue(ClaimTypes.NameIdentifier), appUser.QuickProjectID).FirstOrDefault(p => p.ID == id);

            if (project == null)
            {
                return NotFound();
            }

            ViewBag.Task = new ListService(_context).GetListOfTasks(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            ViewBag.QuickProjectID = appUser.QuickProjectID;

            ViewBag.Theme = appUser.Theme;

            ViewBag.Today = DateTime.Now.ToString("yyyy-MM-dd");

            return View(project);
        }

        // POST: Application/Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Description,IsComplete,Name,RequiredDate")] Project project)
        {
            if (id != project.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        public async Task<IActionResult> Report(int? id)
        {
            if (id == null || _context.Project == null)
            {
                return NotFound();
            }

            ApplicationUser appUser = _context.Users.Where(u => u.Id == this.User.FindFirstValue(ClaimTypes.NameIdentifier)).First();
            var project = new ListService(_context).GetListOfProjects(this.User.FindFirstValue(ClaimTypes.NameIdentifier), appUser.QuickProjectID).FirstOrDefault(p => p.ID == id);

            ViewBag.Theme = appUser.Theme;

            if (project == null)
            {
                return NotFound();
            }

            ViewBag.Progress = Convert.ToDouble(Progress(project));
            ViewBag.User = appUser.FirstName + " " + appUser.LastName;
            ViewBag.Tasks = new ListService(_context).GetListOfTasks(this.User.FindFirstValue(ClaimTypes.NameIdentifier));

            return View(project);
        }

        public double Progress(Project project)
        {
            ApplicationUser appUser = _context.Users.Where(u => u.Id == this.User.FindFirstValue(ClaimTypes.NameIdentifier)).First();
            var projectTasks = new ListService(_context).GetListOfProjectTasks(appUser.Id, project.ID);

            double done = 0;

            foreach (Models.Task t in projectTasks)
            {
                if (t.IsComplete == true)
                {
                    done++;
                }
            }

            if (projectTasks.Count() <= 0)
            {
                return 1;
            }

            double progress = done / projectTasks.Count();
            progress = Math.Round(progress, 2);

            return progress;
        }

        // GET: Application/Projects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Project == null)
            {
                return NotFound();
            }

            ApplicationUser appUser = _context.Users.Where(u => u.Id == this.User.FindFirstValue(ClaimTypes.NameIdentifier)).First();
            var project = new ListService(_context).GetListOfProjects(this.User.FindFirstValue(ClaimTypes.NameIdentifier), appUser.QuickProjectID).FirstOrDefault(p => p.ID == id);

            ViewBag.Theme = appUser.Theme;

            if (project == null)
            {
                return NotFound();
            }

            ViewBag.IsTasksComplete = CheckTaskCompletion(project);

            return View(project);
        }

        // POST: Application/Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Project == null)
            {

GondolinWebApp/GondolinWeb/Areas/Application/Views/Projects/Create.cshtml
@model GondolinWeb.Areas.Application.Models.Project
@using GondolinWeb.Areas.Identity.Data
@using Microsoft.AspNetCore.Identity
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@inject UserManager<ApplicationUser> userManager;
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Application";
    ApplicationUser user = await userManager.GetUserAsync(User);
}

<h1>Create a Project</h1>
<hr class="dashboard-line" />

<div class="row">
    <div class="col-md-4 m-auto">
        <form asp-action="Create" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Name <small class="text-muted">*Required*</small></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <label asp-for="Description" class="control-label">Description <i class="bi bi-question-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="Add further notes if you would like."></i></label>
                <textarea asp-for="Description" class="form-control" rows="3"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <label asp-for="RequiredDate" class="control-label">Required Date <small class="text-muted">*Required*</small></label>
                <input asp-for="RequiredDate" min=@ViewBag.Today type="date" class="form-control" required />
                <span asp-validation-for="RequiredDate" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                    Create
                </button>
                <a class="btn btn-danger" asp-controller="Projects" asp-action="Index">Cancel <i class="bi bi-exclamation-diamond" data-bs-toggle="tooltip" data-bs-placement="right" title="Will not save changes. Return to Project List."></i></a>
                <!-- Modal -->
                <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="staticBackdropLabel">Project is being Created.</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                Would you like to assign tasks to the project?
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-secondary" value="IndexCreate" name="submitbutton">I'm Done</button>
                                <button type="submit" class="btn btn-primary" value="AddTasksCreate" name="submitbutton">Add Tasks</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    }

GondolinWebApp/GondolinWeb/Areas/Application/Views/Projects/Delete.cshtml
@model GondolinWeb.Areas.Application.Models.Project
@using GondolinWeb.Areas.Identity.Data
@using Microsoft.AspNetCore.Identity
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@inject UserManager<ApplicationUser> userManager;
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Application";
    ApplicationUser user = await userManager.GetUserAsync(User);

}

<h1>Delete Confirmation</h1>

<h3 class="text-center">Are you sure you want to delete this project?</h3>
<div class="m-auto w-50 delete-table">
    <dl class="row">
        <dt class="col-sm-4 ps-4">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10 ps-5">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-4 ps-4">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10 ps-5">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-4 ps-4">
            @Html.DisplayNameFor(model => model.RequiredDate)
        </dt>
        <dd class="col-sm-10 ps-5">
            @Model.RequiredDate?.ToShortDateString()
        </dd>
    </dl>

    <form asp-action="Delete">
        @if (ViewBag.IsTasksComplete == true)
        {
            <input type="submit" id="projectDelete" value="Delete" class="btn btn-danger" />
        }
        else
        {
            <label style="color: red;" class="text-center">*All Tasks must be Complete or Removed to delete Projects</label><br />
            <input type="submit" id="projectDelete" disabled value="Delete" class="btn btn-danger" />
        }

        <a class="btn btn-warning" asp-controller="Projects" asp-action="Index">Cancel <i class="bi bi-exclamation-diamond" data-bs-toggle="tooltip" data-bs-placement="right" title="Will not delete Project. Return to Project List."></i></a>
    </form>
</div>

GondolinWebApp/GondolinWeb/Areas/Application/Views/Projects/Edit.cshtml
@model GondolinWeb.Areas.Application.Models.Project
@using GondolinWeb.Areas.Identity.Data
@using Microsoft.AspNetCore.Identity
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@inject UserManager<ApplicationUser> userManager;
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Application";
    ApplicationUser user = await userManager.GetUserAsync(User);
    var TasksExist = false;
}

<head>
    <link rel="stylesheet" href="~/css/TableStyles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/ProjectEdit.css" asp-append-version="true" />
</head>

<h1>Edit Project
</h1>
<hr class="dashboard-line" />

<div class="container w-75">
    <form asp-action="Edit" asp-route-id="@Model.ID" autocomplete="off">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                    <label asp-for="Name" class="control-label">Name  <i class="bi bi-question-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="Change the Name of this Project, and use the Save button to lock in your changes."></i></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequiredDate" class="control-label">Required Date  <i class="bi bi-question-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="Change the Required Date of this Project, and use the Save button to lock in your changes."></i></label>
                    <input asp-for="RequiredDate" type="date" min=@ViewBag.Today class="form-control" id="projectRequiredDate" />
                <span asp-validation-for="RequiredDate" class="text-danger"></span>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                    <label asp-for="Description" class="control-label">Description  <i class="bi bi-question-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="Change the Description of this Project, and use the Save button to lock in your changes."></i></label>
                <textarea asp-for="Description" class="form-control" rows="4"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
    </div>
    <br />
    <div class="form-group text-end">
        <input type="submit" value="Save" class="btn btn-sm btn-primary" />
        <a class="btn btn-sm btn-danger" asp-controller="Projects" asp-action="Index">Cancel <i class="bi bi-exclamation-diamond" data-bs-toggle="tooltip" data-bs-placement="right" title="Will not save changes to Name, Description, or Required Date. Return to Project List."></i></a>
    </div>
    </form>
</div>

<hr class="dashboard-line" />

<div class="table-responsive-sm">
    <div class="row">
        <div class="col">
            <h3>Project Tasks</h3>
        </div>
        <div class="col text-end">
            <a class="btn btn-sm btn-color" asp-controller="Tasks" asp-action="CreateProjectTask" asp-route-ProjectID="@Model.ID">Add a Task <i class="bi bi-question-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="Adds a new Task to this Project."></i></a>
        </div>
    </div>
    <table class="table table-sm table-color rounded-3 overflow-hidden table-hover">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th></th>
                <th>
                    Description
                </th>
                <th></th>
                <th>
                    Category
                </th>
                <th class="text-center" colspan="2">
                    Required Date
                </th>
                <th class="text-center" colspan="2">
                    Is Complete?
                </th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (ViewBag.Task != null)
            {
                @foreach (var Task in ViewBag.Task)
                {
                    if (Task.ProjectID == Model.ID)
                    {
                        TasksExist = true;

                        if (!Task.IsComplete)
                        {
                            <tr>
                                <td colspan="2">
                                    @Task.Name
                                </td>
                                <td colspan="2">
                                    @Task.Description
                                </td>
                                <td class="text-center">
                                    @Task.CategoryName
                                </td>
                                <td class="text-center" colspan="2">
                                    @Task.RequiredDate?.ToShortDateString()
                                </td>
                                @if (Task.IsComplete == false)
                                {
                                    <td class="text-center" colspan="2">
                                        @{
                                            var url = Url.Action("MarkProjectTaskComplete", "Projects", new { @Task.Id }, null);
                                        }
                                        @Html.CheckBox("checkbox" , new { onclick="window.location = '" + url + "'"})
                                    </td>
                                }
                                else
                                {
                                    <td class="text-center" colspan="2">
                                        @{
                                            var url = Url.Action("MarkProjectTaskUnComplete", "Projects", new { @Task.Id }, null);
                                        }
                                        @Html.CheckBox("checkbox" , true, new { onclick="window.location = '" + url + "'"})
                                    </td>
                                }
                                <td class="text-center" colspan="3">
                                    <a class="btn btn-sm btn-primary" asp-controller="Tasks" asp-action="EditProjectTask" asp-route-id="@Task.Id">Edit</a>
                                    <a class="btn btn-sm btn-danger" asp-action="RemoveTask" asp-route-taskId="@Task.Id" asp-route-projectID="@Model.ID">Remove <i class="bi bi-question-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="Removes Task from this Project, but does not delete it."></i></a>
                                </td>
                            </tr>
                        }
                    }
                }
            }
            @if (ViewBag.Task != null)
            {
                @foreach (var Task in ViewBag.Task)
                {
                    if (Task.ProjectID == Model.ID)
                    {
                        TasksExist = true;

                        if (Task.IsComplete)
                        {
                            <tr>
                                <td colspan="2">
                                    @Task.Name
                                </td>
                                <td colspan="2">
                                    @Task.Description
                                </td>
                                <td class="text-center">
                                    @Task.CategoryName
                                </td>
                                <td class="text-center" colspan="2">
                                    @Task.RequiredDate?.ToShortDateString()
                                </td>
                                @if (Task.IsComplete == false)
                                {
                                    <td class="text-center" colspan="2">
                                        @{
                                            var url = Url.Action("MarkProjectTaskComplete", "Projects", new { @Task.Id }, null);
                                        }
                                        @Html.CheckBox("checkbox" , new { onclick="window.location = '" + url + "'"})
                                    </td>
                                }
                                else
                                {
                                    <td class="text-center" colspan="2">
                                        @{
                                            var url = Url.Action("MarkProjectTaskUnComplete", "Projects", new { @Task.Id }, null);
                                        }
                                        @Html.CheckBox("checkbox" , true, new { onclick="window.location = '" + url + "'"})
                                    </td>
                                }
                                <td class="text-center" colspan="3">
                                    <a class="btn btn-sm btn-primary" asp-controller="Tasks" asp-action="EditProjectTask" asp-route-id="@Task.Id">Edit</a>
                                    <a class="btn btn-sm btn-danger" asp-action="RemoveTask" asp-route-taskId="@Task.Id" asp-route-projectID="@Model.ID">Remove <i class="bi bi-question-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="Removes Task from this Project, but does not delete it."></i></a>
                                </td>
                            </tr>
                        }
                    }
                }
            }
            @if (!TasksExist)
            {
                <tr class="text-center">
                    <td colspan="12"><h4><em>This Project has no Tasks. Use the button above or the lists below to add Tasks.</em></h4></td>
                </tr>
            }
        </tbody>
    </table>
</div><br />

<hr class="dashboard-line" />

<div class="container table-responsive-sm">
    <div class="row">
        <div class="col-md">
            <h3>Favorite Tasks</h3>
            <table class="table table-sm table-color rounded-3 overflow-hidden table-hover m-auto">
                <thead>
                    <tr>
                        <th>
                            Name
                        </th>
                        <th>
                            Description
                        </th>
                        <th></th>
                        <th class="text-center">
                            Category
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var Task in ViewBag.Task)
                    {
                        if (Task.IsFavorite)
                        {
                            <tr>
                                <td>
                                    @Task.Name
                                </td>
                                <td colspan="2">
                                    @Task.Description
                                </td>
                                <td class="text-center">
                                    @Task.CategoryName
                                </td>
                                <td class="text-center">
                                    <a class="btn btn-sm btn-primary" asp-controller="Tasks" asp-action="AddFavoriteTask" asp-route-taskID="@Task.Id" asp-route-projectID="@Model.ID">Add <i class="bi bi-question-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="Uses this Task template to create a new Task for this Project."></i></a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table><br />
        </div>
        <div class="col-md">
    <h3>Tasks not assigned to a Project</h3>
    <table class="table table-sm table-color rounded-3 overflow-hidden table-hover m-auto">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Description
                </th>
                <th></th>
                        <th class="text-center">
                    Category
                </th>
                <th class="text-center">
                    Required Date
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var Task in ViewBag.Task)
            {
                if (Task.ProjectID == ViewBag.QuickProjectID && !Task.IsComplete && !Task.IsFavorite)
                {
                    <tr>
                        <td>
                            @Task.Name
                        </td>
                        <td colspan="2">
                            @Task.Description
                        </td>
                                <td class="text-center">
                            @Task.CategoryName
                        </td>
                                <td class="text-center">
                                    @Task.RequiredDate?.ToShortDateString()
                        </td>
                        <td class="text-center">
                            <a class="btn btn-sm btn-primary" asp-action="AddTask" asp-route-taskId="@Task.Id" asp-route-projectID="@Model.ID">Add <i class="bi bi-question-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="Adds this Task to the current Project."></i></a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }